name : first_answer
on: push

jobs:
  job1:
    name: First_job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: step two
        run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: step two
        run: date 

  job1:
    name: Third_Job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: step two
        run: date

  job1:
    name: Forth_job
    needs: [ job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: step two
        run: date
